dependencies:
  - name: alertmanager
    version: 0.0.8
    #e2e-repository: file://../alertmanager
    repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

  - name: prometheus
    version: 0.0.13
    #e2e-repository: file://../prometheus
    repository: file://../prometheus

  - name: exporter-kube-controller-manager
    version: 0.1.4
    #e2e-repository: file://../exporter-kube-controller-manager
    repository: file://../exporter-kube-controller-manager

  - name: exporter-kube-dns
    version: 0.1.3
    #e2e-repository: file://../exporter-kube-dns
    repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

  - name: exporter-kube-etcd
    version: 0.1.6
    #e2e-repository: file://../exporter-kube-etcd
    repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

  - name: exporter-kube-scheduler
    version: 0.1.4
    #e2e-repository: file://../exporter-kube-scheduler
    repository: file://../exporter-kube-scheduler

  - name: exporter-kube-state
    version: 0.1.7
    #e2e-repository: file://../exporter-kube-state
    repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

  - name: exporter-kubelets
    version: 0.2.1
    #e2e-repository: file://../exporter-kubelets
    repository: file://../exporter-kubelets

  - name: exporter-kubernetes
    version: 0.1.3
    #e2e-repository: file://../exporter-kubernetes
    repository: file://../exporter-kubernetes

  - name: exporter-node
    version: 0.1.3
    #e2e-repository: file://../exporter-node
    repository: file://../exporter-node
    condition: deployExporterNode

  - name: grafana
    version: 0.0.10
    #e2e-repository: file://../grafana
    repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
    condition: deployGrafana
